eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8080/eureka/
feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 10000
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity
server:
    port: 8181
spring:
    application:
        name: account-server
    cloud:
        alibaba:
            seata:
                tx-service-group: my_test_tx_group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: admin123456
        url: jdbc:mysql://124.70.153.227:3306/seata_acount
        username: root
