eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8080/eureka/
feign:
    hystrix:
        enabled: false
    client:
        config:
            default:
                connectTimeout: 60000
                readTimeout: 60000
logging:
    level:
        io:
            seata: info
        io.seata.sample.dao.*: debug    #这是你的mapper包路径。org.spring.springboot
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity
server:
    port: 8180
spring:
    application:
        name: order-server
    cloud:
        alibaba:
            seata:
                tx-service-group: my_test_tx_group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: admin123456
        url: jdbc:mysql://124.70.153.227:3306/seat-order
        username: root
